learninglog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('users.urls','users'), namespace='users')),
    path('', include(('log.urls','log'), namespace='log')),
]

log/urls.py
"""defining url for learning log."""
from django.urls import path
from . import views 

urlpatterns = [
     # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('<int:topic_id>/topic/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('<int:topic_id>/new_entry/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('<int:entry_id>/edit_entry/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # logout.
    path("logout", views.logout_request, name="logout"),
    # Registration page.
    path('register/', views.register, name='register'),


]

log/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """info about topic."""
    text = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """represent as string."""
        return self.text

class Entry(models.Model):
    """info about entry."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """represent as strings."""
        if self.text >= self.text[:50]:
            return self.text[:50] + "..."
        else:
            return self.text
    

users/models.py
from django.db import models

# Create your models here.

log/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widget = {'text': forms.Textarea(attrs={'col': 80})}

log/views.py
from django.shortcuts import render, redirect #render returns the complete template view.
#redirect the page to topics after submitted form.  
from .models import Topic, Entry
from django.contrib.auth.decorators import login_required
from .forms import TopicForm, EntryForm
from django.http import Http404

# Create your views here.
def index(request):
    """contains info of index page."""
    return render(request, 'log/index.html')

@login_required
def topics(request):
    """contains info of topics page."""
    topics = Topic.objects.filter(owner=request.user).order_by('date')
    context = {'topics': topics}
    return render(request, 'log/topics.html', context)

@login_required
def topic(request, topic_id):
    """contains info of each topic with entries."""
    topic = Topic.objects.get(id=topic_id)
    "make sure current user belongs to logged in user."
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by ('-date')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'log/topic.html', context)

@login_required
def new_topic(request):
    """direct user inputted data or blank form."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('log:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'log/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    "make sure current user belongs to logged in user."
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('log:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'log/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    "make sure current user belongs to logged in user."
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('log:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'log/edit_entry.html', context)

users/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm

def logout_request(request):
    logout(request)
    return render(request, 'registration/logout.html')

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('log:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

log/templates/log/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}  

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'log:index'%}">
        Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'log:topics'%}">
              Topics</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

log/templates/log/edit_entry.html
{% extends "log/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  
  <h2><a href="{% url 'log:topic' topic.id %}">{{topic}}</a></h2>
  
  <h5>Edit Entry:</h5>  

{% endblock page_header %}

{% block content %}
  <form action="{% url 'log:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>
    
{% endblock content %}

log/templates/log/index.html
{% extends "log/base.html" %} 

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

log/templates/log/new_entry.html
{% extends "log/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  
  <h2><a href="{% url 'log:topic' topic.id %}">{{topic}}</a></h2>
  
  <h5>Add a new Entry:</h5>  

{% endblock page_header %}

{% block content %}
  <form action="{% url 'log:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>
    
{% endblock content %}

log/templates/log/new_topic.html
{% extends "log/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  <h5 class="lead">Add a new Topic:</h5>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'log:new_topic' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}

  </form>
    
{% endblock content %}

log/templates/log/topic.html
{% extends 'log/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'log:new_entry' topic.id %}">Add new entry</a>
  </p>

  <ul>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date|date:'M d, Y H:i' }}
        <small><a href="{% url 'log:edit_entry' entry.id %}">
            edit entry</a>
        </small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

log/templates/log/topics.html
{% extends "log/base.html" %}

{% block page_header %}
  <h2>Topics</h2>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li><h4>
        <a href="{% url 'log:topic' topic.id %}">{{ topic }}</a>
      </h4></li>
    {% empty %}
      <li><h4>No topics have been added yet.</h4></li>
    {% endfor %}
  </ul>

  <h5><a href="{% url 'log:new_topic' %}">Add a new topic</a></h5>

{% endblock content %}